name: dinder
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  cloud_firestore: ^4.3.1
  email_validator: ^2.1.17
  file_picker: ^5.2.5
  firebase_auth: ^4.2.5
  firebase_storage: ^11.0.10
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_focus_watcher: ^2.0.0
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  hexcolor: ^3.0.1
  logger: ^1.1.0
  provider: ^6.0.5
  swipeable_card_stack: ^0.0.5
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/carousel/
