// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNBJbv6grgHXs-6kOhqPPnDBLuu65mNDs',
    appId: '1:688499823351:web:33bd8e2e54cb6d3a08f9f2',
    messagingSenderId: '688499823351',
    projectId: 'dinder-app1',
    authDomain: 'dinder-app1.firebaseapp.com',
    storageBucket: 'dinder-app1.appspot.com',
    measurementId: 'G-GQRNM7QDC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUx_5XyKp8Mj1hDlWoNZdja5LIFHzDY_s',
    appId: '1:688499823351:android:699821d2621630ff08f9f2',
    messagingSenderId: '688499823351',
    projectId: 'dinder-app1',
    storageBucket: 'dinder-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2gX3oNmYrQWkxx_piaYXUwMaSgvV6vSA',
    appId: '1:688499823351:ios:68186fd7a27efbb408f9f2',
    messagingSenderId: '688499823351',
    projectId: 'dinder-app1',
    storageBucket: 'dinder-app1.appspot.com',
    iosClientId: '688499823351-rnlj0pfbngajc7eqfh464924andsupin.apps.googleusercontent.com',
    iosBundleId: 'com.example.dinder',
  );
}
